import { FontFamily as FontFamily, FontSizes as FontSizes } from "./data-structures";

export const FontSizesList: FontSizes[] = [
  { id: 8, name: '8' },
  { id: 9, name: '9' },
  { id: 10, name: '10' },
  { id: 11, name: '11' },
  { id: 12, name: '12' },
  { id: 14, name: '14' },
  { id: 16, name: '16' },
  { id: 18, name: '18' },
  { id: 20, name: '20' },
  { id: 22, name: '22' },
  { id: 24, name: '24' },
  { id: 26, name: '26' },
  { id: 28, name: '28' },
  { id: 30, name: '30' },
  { id: 36, name: '36' },
  { id: 48, name: '48' },
  { id: 60, name: '60' },
  { id: 72, name: '72' },
  { id: 84, name: '84' },
  { id: 108, name: '108' },
];

export const FontFamiliesList: FontFamily[] = [
  {
    name: 'Arial',
    category: 'sans-serif',
    stack: ['Arial', 'Helvetica', '"Helvetica Neue"', 'sans-serif'],
  },
  {
    name: 'Calibri',
    category: 'sans-serif',
    stack: [
      'Calibri',
      'Candara',
      'Segoe',
      '"Segoe UI"',
      'Optima',
      'Arial',
      'sans-serif',
    ],
  },
  {
    name: 'Century Gothic',
    category: 'sans-serif',
    stack: ['"Century Gothic"', 'CenturyGothic', 'AppleGothic', 'sans-serif'],
  },
  {
    name: 'Gill Sans',
    category: 'sans-serif',
    stack: ['"Gill Sans"', '"Gill Sans MT"', 'Calibri', 'sans-serif'],
  },
  {
    name: 'Tahoma',
    category: 'sans-serif',
    stack: ['Tahoma', 'Verdana', 'Segoe', 'sans-serif'],
  },
  {
    name: 'Trebuchet MS',
    category: 'sans-serif',
    stack: [
      '"Trebuchet MS"',
      '"Lucida Grande"',
      '"Lucida Sans Unicode"',
      'Tahoma',
      'sans-serif',
    ],
  },
  {
    name: 'Verdana',
    category: 'sans-serif',
    stack: ['Verdana', 'Geneva', 'sans-serif'],
  },
  {
    name: 'Book Antiqua',
    category: 'serif',
    stack: [
      '"Book Antiqua"',
      'Palatino',
      '"Palatino Linotype"',
      '"Palatino LT STD"',
      'Georgia',
      'serif',
    ],
  },
  {
    name: 'Cambria',
    category: 'serif',
    stack: ['Cambria', 'Georgia', 'serif'],
  },
  {
    name: 'Garamond',
    category: 'serif',
    stack: [
      'Garamond',
      'Baskerville',
      '"Baskerville Old Face"',
      '"Hoefler Text"',
      '"Times New Roman"',
      'serif',
    ],
  },
  {
    name: 'Georgia',
    category: 'serif',
    stack: ['Georgia', 'Times', '"Times New Roman"', 'serif'],
  },
  {
    name: 'Goudy Old Style',
    category: 'serif',
    stack: [
      '"Goudy Old Style"',
      'Garamond',
      '"Big Caslon"',
      '"Times New Roman"',
      'serif',
    ],
  },
  {
    name: 'Lucida Bright',
    category: 'serif',
    stack: ['"Lucida Bright"', 'Georgia', 'serif'],
  },
  {
    name: 'Palatino',
    category: 'serif',
    stack: [
      'Palatino',
      '"Palatino Linotype"',
      '"Book Antiqua"',
      'Georgia',
      'serif',
    ],
  },
  {
    name: 'Baskerville',
    category: 'serif',
    stack: [
      'Baskerville',
      '"Baskerville Old Face"',
      '"Hoefler Text"',
      'Garamond',
      '"Times New Roman"',
      'serif',
    ],
  },
  {
    name: 'TimesNewRoman',
    category: 'serif',
    stack: [
      'TimesNewRoman',
      '"Times New Roman"',
      'Times',
      'Baskerville',
      'Georgia',
      'serif',
    ],
  },
  {
    name: 'Courier New',
    category: 'monospace',
    stack: [
      '"Courier New"',
      'Courier',
      '"Lucida Sans Typewriter"',
      '"Lucida Typewriter"',
      'Georgia',
      'monospace',
    ],
  },
  {
    name: 'Lucida Sans Typewriter',
    category: 'monospace',
    stack: [
      '"Lucida Sans Typewriter"',
      '"Lucida Console"',
      'monaco',
      '"Bitstream Vera Sans Mono"',
      'monospace',
    ],
  },
  {
    name: 'Copperplate',
    category: 'fantasy',
    stack: ['Copperplate', '"Copperplate Gothic Light"', 'fantasy'],
  },
  {
    name: 'Brush Script MT',
    category: 'script',
    stack: ['"Brush Script MT"', 'cursive'],
  },
];
